spring.application.name: domain-service

server.port: 8080

domain:
  extensions:
  - com
  - org
  - io
  - fr
  - es
  - net
  - ai
  - cat

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # magic fallback url for eureka